<?php

namespace CCM\InventarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InventarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienRepository extends EntityRepository
{


    public function findBien($noInventario)
    {
        $em = $this->getEntityManager();
        $dql = 'SELECT b FROM InventarioBundle:Bien b WHERE b.noInventario = :noInventario';
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('noInventario', $noInventario);
        return $consulta->getOneOrNullResult();
    }

    public function findCategoria($tipo)
    {
        $em = $this->getEntityManager();
        $dql = 'SELECT b FROM InventarioBundle:Bien b WHERE b.categoria = :tipo ';
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('tipo', $tipo);
        return $consulta->getResult();
    }





}


